### ISSUE TITLE
Syntax highlighting *does not* work with neovim 0.3.8 macOS / installed via Plug.

### ISSUE THREAD

**Issue by pavelz** [udalov/kotlin-vim#33]
There are no errors - tried disabling all other plugins but no cigar. No errors or warnings either.

**Comment by udalov** [comment]
The plugin only highlights syntactic structure of the source code. Reporting compilation errors and warnings would require to run the Kotlin compiler front-end, which is very slow for a use case like a Vim plugin. Or do you mean something else by errors/warnings?

**Comment by pavelz** [comment]
I meant with configuration described in the header, syntax is not highlighted
Also explicitly doing: syntax on , set filetype=kotlin does not have any effect on *.kt files. To this effect, sometime plugins generate neovim errors -  this was not the case here.

**Comment by sjrct** [comment]
Worked out of the box for me with neovim v0.3.8 on macos catalina 10.15.3, but I was using pathogen.

**Comment by pavelz** [comment]
Started working with neovim 0.4.3, closing.
